### ISSUE TITLE
Underlined vectors

### ISSUE THREAD

**Issue by moorepants** [gilbertgede/idetc-2013-paper#1]
I just found underlined vectors as odd. Seems like the norm is overline. I'd like to change them unless there is some reason for underlines.

**Comment by gilbertgede** [comment]
That's fine with me, I think they might be there because of how one of us learned to write vectors down by hand. I like keeping the bold for "math vectors" and the over/under-line for "3D vectors" though.

**Comment by moorepants** [comment]
The notations is not consistent in the paper. For example in the Lagrange section the q doesn't have a bar (or underline) and it is a vector. Also in the Kane section the vector function f doesn't have bars or underlines. There needs to be a little work with this. I'm about to push some changes. I'll try the bar instead of underline for vectors to see if it looks better. But will leave some TODO notes to point out these inconsistencies.
